library(teal.modules.hermes)
library(teal.modules.general)
library(scda.2022)
library(nestcolor)

options(shiny.useragg = FALSE)

# code>
mae <- hermes::multi_assay_experiment
mae_data <- dataset("MAE", mae)

adtte <- scda::synthetic_cdisc_data("rcd_2022_06_27")$adtte %>%
  dplyr::mutate(is_event = CNSR == 0)

data <- teal_data(
  dataset(
    "ADTTE",
    adtte,
    code = 'adtte <- scda::synthetic_cdisc_data("rcd_2022_06_27")$adtte %>%
      dplyr::mutate(is_event = CNSR == 0)'
  ),
  dataset("MAE", mae)
)

app <- init(
  data = data,
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c("Info about input data source" = "This app uses MultiplAssayExperiment data object randomly generated by `scda`, `scda.2022` & `hermes` R packages"),
      tables = list(`NEST packages used in this demo app` = data.frame(
        Packages = c("teal.modules.hermes", "teal.modules.general", "scda", "scda.2022", "hermes")
      ))
    ),
    tm_g_quality(
      label = "Quality Control",
      mae_name = "MAE"
    ),
    tm_g_pca(
      label = "PCA plot",
      mae_name = "MAE"
    ),
    teal.modules.hermes::tm_g_scatterplot(
      label = "Scatterplot",
      mae_name = "MAE"
    ),
    tm_g_boxplot(
      label = "Boxplot",
      mae_name = "MAE"
    ),
    tm_g_barplot(
      label = "Barplot",
      mae_name = "MAE"
    ),
    tm_g_volcanoplot(
      label = "Volcanoplot",
      mae_name = "MAE"
    ),
    tm_g_forest_tte(
      label = "Forestplot",
      adtte_name = "ADTTE",
      mae_name = "MAE"
    ),
    tm_g_km(
      label = "Kaplan-Meier",
      adtte_name = "ADTTE",
      mae_name = "MAE"
    )
  ),
  header = div(
    class = "",
    style = "margin-bottom: 2px;",
    tags$h1(
      "Example App with teal.modules.hermes modules",
      tags$span("SPA", class = "pull-right")
    )
  ),
  footer = tags$p(
    actionLink("showAboutModal", "About,"),
    tags$a(
      href = "https://github.com/insightsengineering/teal.gallery/tree/main/RNA-seq",
      target = "_blank",
      "Source Code,"
    ),
    tags$a(
      href = "https://github.com/insightsengineering/teal.gallery/issues",
      target = "_blank",
      "Report Issues"
    )
  )
)

body(app$server)[[length(body(app$server)) + 1]] <- quote(
  observeEvent(input$showAboutModal, {
    showModal(modalDialog(
      tags$p("This teal app is brought to you by the NEST Team at Roche/Genentech. For more information, please visit:"),
      tags$ul(
        tags$li(tags$a(
          href = "https://github.com/insightsengineering", "Insights Engineering",
          target = "blank"
        )),
        tags$li(tags$a(
          href = "https://pharmaverse.org", "Pharmaverse",
          target = "blank"
        ))
      ),
      easyClose = TRUE
    ))
  })
)

## Not run:
shinyApp(app$ui, app$server)
