library(teal.modules.clinical)
library(teal.modules.general)
options(shiny.useragg = FALSE)

## Data reproducible code ----
data <- teal_data()
data <- within(data, {
  library(nestcolor)

  ADSL <- random.cdisc.data::cadsl
  ADMH <- random.cdisc.data::cadmh
  ADAE <- random.cdisc.data::cadae
  ADCM <- random.cdisc.data::cadcm
  ADVS <- random.cdisc.data::cadvs
  ADLB <- random.cdisc.data::cadlb

  ## Modify ADCM
  ADCM$CMINDC <- paste0("Indication_", as.numeric(ADCM$CMDECOD))
  ADCM$CMDOSE <- 1
  ADCM$CMTRT <- ADCM$CMCAT
  ADCM$CMDOSU <- "U"
  ADCM$CMROUTE <- "CMROUTE"
  ADCM$CMDOSFRQ <- "CMDOSFRQ"
  ADCM$CMASTDTM <- ADCM$ASTDTM
  ADCM$CMAENDTM <- ADCM$AENDTM

  teal.data::col_labels(
    ADCM[c("CMINDC", "CMTRT", "ASTDY", "AENDY")]
  ) <- c(
    "Indication",
    "Reported Name of Drug, Med, or Therapy",
    "Study Day of Start of Medication",
    "Study Day of End of Medication"
  )

  ## Modify ADHM
  ADMH[["MHDISTAT"]] <- "ONGOING"
  teal.data::col_labels(ADMH[c("MHDISTAT")]) <- c("Status of Disease")
})

join_keys(data) <- default_cdisc_join_keys[c("ADSL", "ADMH", "ADAE", "ADCM", "ADVS", "ADLB")]

## App configuration ----

## Define variable inputs
aeterm_input <- variables("AETERM", "AETERM")

cmtrt_input <- variables("CMTRT", "CMTRT")

cmindc_input <- variables("CMINDC", "CMINDC")

atirel_input <- variables("ATIREL", "ATIREL")

cmdecod_input <- variables("CMDECOD", "CMDECOD")

## App header and footer ----
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
app_source <- "https://github.com/insightsengineering/teal.gallery/tree/main/patient-profile"
gh_issues_page <- "https://github.com/insightsengineering/teal.gallery/issues"

header <- tags$span(
  style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
  tags$span("Patient-profile teal app", style = "font-size: 30px;"),
  tags$span(
    style = "display: flex; align-items: center;",
    tags$img(src = nest_logo, alt = "NEST logo", height = "45px", style = "margin-right:10px;"),
    tags$span(style = "font-size: 24px;", "NEST @ Roche")
  )
)

footer <- tags$p(
  "This teal app is brought to you by the NEST Team at Roche/Genentech.
        For more information, please visit:",
  tags$a(href = app_source, target = "_blank", "Source Code"), ", ",
  tags$a(href = gh_issues_page, target = "_blank", "Report Issues")
)

app <- init(
  data = data,
  filter = teal_slices(
    count_type = "all",
    teal_slice(dataname = "ADSL", varname = "SEX"),
    teal_slice(dataname = "ADSL", varname = "AGE")
  ),
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c(
        "Info about input data source" =
          "This app uses CDISC ADaM datasets randomly generated by `random.cdisc.data` R packages"
      ),
      tables = list(
        `NEST packages used in this demo app` = data.frame(
          Packages = c("teal.modules.general", "teal.modules.clinical", "random.cdisc.data")
        )
      )
    ),
    tm_t_pp_basic_info(
      label = "Basic Info",
      dataname = "ADSL",
      patient_col = "USUBJID",
      vars = variables(selected = c("ARM", "AGE", "SEX", "COUNTRY", "RACE", "EOSSTT"), multiple = TRUE)
    ),
    tm_t_pp_medical_history(
      label = "Medical History",
      parentname = "ADSL",
      dataname = "ADMH",
      patient_col = "USUBJID",
      mhterm = variables("MHTERM", "MHTERM"),
      mhbodsys = variables("MHBODSYS", "MHBODSYS"),
      mhdistat = variables("MHDISTAT", "MHDISTAT"),
    ),
    tm_t_pp_prior_medication(
      label = "Prior Medication",
      parentname = "ADSL",
      patient_col = "USUBJID",
      atirel = atirel_input,
      cmdecod = cmdecod_input,
      cmindc = cmindc_input,
      cmstdy = variables("ASTDY", "ASTDY")
    ),
    tm_g_pp_vitals(
      label = "Vitals",
      parentname = "ADSL",
      dataname = "ADVS",
      patient_col = "USUBJID",
      plot_height = c(600L, 200L, 2000L),
      paramcd = variables("PARAMCD", "PARAMCD"),
      xaxis = variables("ADY", "ADY"),
      aval_var = variables("AVAL", "AVAL")
    ),
    tm_g_pp_therapy(
      label = "Therapy",
      parentname = "ADSL",
      patient_col = "USUBJID",
      plot_height = c(600L, 200L, 2000L),
      atirel = atirel_input,
      cmdecod = cmdecod_input,
      cmindc = cmindc_input,
      cmdose = variables("CMDOSE", "CMDOSE"),
      cmtrt = cmtrt_input,
      cmdosu = variables("CMDOSU", "CMDOSU"),
      cmroute = variables("CMROUTE", "CMROUTE"),
      cmdosfrq = variables("CMDOSFRQ", "CMDOSFRQ"),
      cmstdy = variables("ASTDY", "ASTDY"),
      cmendy = variables("AENDY", "AENDY")
    ),
    tm_g_pp_adverse_events(
      label = "Adverse Events",
      parentname = "ADSL",
      dataname = "ADAE",
      patient_col = "USUBJID",
      plot_height = c(600L, 200L, 2000L),
      aeterm = aeterm_input,
      tox_grade = variables("AETOXGR", "AETOXGR"),
      causality = variables("AEREL", "AEREL"),
      outcome = variables("AEOUT", "AEOUT"),
      action = variables("AEACN", "AEACN"),
      time = variables("ASTDY", "ASTDY"),
      decod = NULL
    ),
    tm_t_pp_laboratory(
      label = "Lab Values",
      parentname = "ADSL",
      dataname = "ADLB",
      patient_col = "USUBJID",
      paramcd = variables("PARAMCD", "PARAMCD"),
      param = variables("PARAM", "PARAM"),
      time_points = variables("ADY", "ADY"),
      anrind = variables("ANRIND", "ANRIND"),
      aval_var = variables("AVAL", "AVAL"),
      avalu_var = variables("AVALU", "AVALU")
    ),
    tm_g_pp_patient_timeline(
      label = "Patient Timeline",
      parentname = "ADSL",
      dataname_adcm = "ADCM",
      dataname_adae = "ADAE",
      patient_col = "USUBJID",
      plot_height = c(600L, 200L, 2000L),
      font_size = c(15L, 8L, 25L),
      cmdecod = cmdecod_input,
      aeterm = aeterm_input,
      aetime_start = variables("ASTDTM", "ASTDTM"),
      aetime_end = variables("AENDTM", "AENDTM"),
      dstime_start = variables("CMASTDTM", "CMASTDTM"),
      dstime_end = variables("CMAENDTM", "CMAENDTM"),
      aerelday_start = variables("ASTDY", "ASTDY"),
      aerelday_end = variables("AENDY", "AENDY"),
      dsrelday_start = variables("ASTDY", "ASTDY"),
      dsrelday_end = variables("AENDY", "AENDY")
    )
  )
) |>
  modify_title(
    title = "Patient Profile Analysis Teal Demo App",
    favicon = nest_logo
  ) |>
  modify_header(header) |>
  modify_footer(footer)

shinyApp(app$ui, app$server)
