library(teal.modules.general)
options(
  shiny.useragg = FALSE,
  teal.ggplot2_args = teal.widgets::ggplot2_args(labs = list(caption = "NEST PROJECT"))
)

## Data reproducible code ----
data <- teal_data()
data <- within(data, {
  library(random.cdisc.data)
  library(dplyr)
  library(tidyr)
  library(ggExtra)
  library(ggpmisc)
  library(ggpp)
  library(goftest)
  library(gridExtra)
  library(htmlwidgets)
  library(jsonlite)
  library(lattice)
  library(MASS)
  library(rlang)
  library(rtables)
  library(nestcolor)
  library(broom)
  library(colourpicker)
  library(sparkline)


  ADSL <- radsl(seed = 1)
  ADRS <- radrs(ADSL, seed = 1)
  ADLB <- radlb(ADSL, seed = 1)
  ADLBPCA <- ADLB %>%
    dplyr::select(USUBJID, STUDYID, SEX, ARMCD, AVAL, AVISIT, PARAMCD) %>%
    tidyr::pivot_wider(
      values_from = "AVAL",
      names_from = c("PARAMCD", "AVISIT"),
      names_sep = " - "
    )
})

join_keys(data) <- default_cdisc_join_keys[c("ADSL", "ADRS", "ADLB", "ADLBPCA")]

app <- init(
  data = data,
  filter = teal_slices(
    count_type = "all",
    teal_slice(dataname = "ADSL", varname = "SEX"),
    teal_slice(dataname = "ADSL", varname = "AGE")
  ),
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c(
        "Info about input data source" =
          "This app uses CDISC ADaM datasets randomly generated by `random.cdisc.data` R packages"
      ),
      tables = list(
        `NEST packages used in this demo app` = data.frame(Packages = c("teal.modules.general", "random.cdisc.data"))
      )
    ),
    tm_file_viewer(
      label = "File viewer",
      input_path = list(
        png = "https://www.r-project.org/logo/Rlogo.png",
        Rmd = "https://raw.githubusercontent.com/tidyverse/dplyr/master/README.Rmd",
        pdf = "https://cran.r-project.org/web/packages/shinyTree/shinyTree.pdf",
        "example directory" = "./packrat/desc/"
      )
    ),
    tm_data_table("Data Table"),
    tm_variable_browser("Variable Browser"),
    tm_missing_data("Missing Data"),
    tm_g_distribution("Distribution"),
    # tm_outliers("Outliers"),
    tm_g_association(),
    tm_g_bivariate(
      transformators = list(
        teal_transform_filter(
          picks(
            datasets("ADLB"),
            variables(choices = c("PARAMCD", "AVISIT"), selected = c("PARAMCD", "AVISIT"), fixed = TRUE),
            values(multiple = FALSE)
          )
        )
      ),
      use_density = FALSE,
      plot_height = c(600L, 200L, 2000L),
      ggtheme = "gray"
    ),
    tm_a_regression(
      label = "Regression",
      transformators = list(
        teal_transform_filter(picks(datasets("ADRS"), variables("PARAMCD"), values(selected = "BESRSPI")))
      )
    ),
    tm_g_response(
      transformators = list(
        teal_transform_filter(picks(datasets("ADRS"), variables("PARAMCD"), values(selected = "BESRSPI")))
      ),
      coord_flip = FALSE
    ),
    tm_g_scatterplotmatrix(label = "Scatterplot Matrix"),
    tm_g_scatterplot("Scatterplot", size = 3, alpha = 1, plot_height = c(600L, 200L, 2000L)),
    tm_t_crosstable("Table Choices"),
    tm_a_pca("Principal Component Analysis", plot_height = c(600L, 200L, 2000L), plot_width = c(600L, 200L, 2000L))
  )
) |>
  modify_title(
    title = "Exploratory Analysis Teal Demo App",
    favicon = "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
  ) |>
  modify_header(
    tags$span(
      style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
      tags$span("My first teal app", style = "font-size: 30px;"),
      tags$span(
        style = "display: flex; align-items: center;",
        tags$img(
          src = "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png",
          alt = "NEST logo", height = "45px", style = "margin-right:10px;"
        ),
        tags$span(style = "font-size: 24px;", "NEST @ Roche")
      )
    )
  ) |>
  modify_footer(
    tags$p(
      "This teal app is brought to you by the NEST Team at Roche/Genentech.
        For more information, please visit:",
      tags$a(
        href = "https://github.com/insightsengineering/teal.gallery/tree/main/exploratory",
        target = "_blank", "Source Code"
      ), ", ",
      tags$a(
        href = "https://github.com/insightsengineering/teal.gallery/issues",
        target = "_blank", "Report Issues"
      )
    )
  )

shinyApp(app$ui, app$server)
