---
name: Deploy Apps to Stable and Dev 🚀

on:
  push:
    branches:
      - main
      - dev
    paths:
      - RNA-seq/**
      - basic-teal/**
      - delayed-data/**
      - teal-as-shiny-module/**
      - custom-transform/**
      - efficacy/**
      - exploratory/**
      - longitudinal/**
      - early-dev/**
      - patient-profile/**
      - python/**
      - safety/**
  workflow_dispatch:
  schedule:
    - cron: "12 3 * * *"

jobs:
  deploy_main:
    uses: ./.github/workflows/deploy.yml
    with:
      channel: stable
      target-branch: refs/heads/main
    secrets: inherit
  deploy_dev:
    uses: ./.github/workflows/deploy.yml
    with:
      channel: dev
      target-branch: refs/heads/dev
    secrets: inherit
